name: Hexalith EasyAuthentication Build
on:
  push:
    paths-ignore:
      - '**/*.md'
      - 'mkdocs.yml'
      - 'docs/**/*'
    branches: 
      - main
      - release-*
    tags:
      - 'v*'
  pull_request:
    branches: 
      - master
      - release-*
permissions:
  contents: read
  packages: write
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
jobs:
  publish:
    runs-on: ubuntu-latest
    name: Build, Test, Publish
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Initialize HexalithApp submodule
      run: |
          git submodule init HexalithApp
          git submodule update HexalithApp
    - name: Setup .NET 9.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Add Aspire Workloads
      run: |
        dotnet workload install aspire
    - name: Build Version
      run: |
        dotnet tool install --global minver-cli --version 5.0.0
        version=$(minver -t v -v e -d preview)
        echo "MINVERVERSIONOVERRIDE=$version" >> $GITHUB_ENV
        echo "VERSION=$version" >> $GITHUB_ENV
        echo "VERSION=$version"
    - name: Unit Tests
      run: |
        dotnet test -c Release --no-restore --no-build ./test/Hexalith.EasyAuthentication.UnitTests/Hexalith.EasyAuthentication.UnitTests.csproj
    - name: Publish release packages to Nuget
      if: startswith(github.ref, 'refs/tags/v') 
      run: |
        dotnet nuget push './src/**/*.nupkg' --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate    
    - name: Check the container registry parameters
      run: |
        echo "Registry: ${{ vars.AZURE_REGISTRY }}"
        echo "User Name: ${{ secrets.AZURE_APPLICATIONID }}"
        echo "Password: ${{ secrets.AZURE_APPLICATIONSECRET }}"
    - name: Login to the container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ vars.AZURE_REGISTRY }}
        username: ${{ secrets.AZURE_APPLICATIONID }}
        password: ${{ secrets.AZURE_APPLICATIONSECRET }}
    - name: Publish and push the Document Web server container images to the container registry
      run: |
          dotnet publish './HexalithApp/src/HexalithApp.WebServer/HexalithApp.WebServer.csproj' /t:PublishContainer --configuration Release --os linux --arch x64 -p:ContainerImageTags='"${{ env.VERSION }};latest"' -p:ContainerRegistry=${{ vars.AZURE_REGISTRY }} -p:ContainerRepository='security-web'
          dotnet publish './HexalithApp/src/HexalithApp.ApiServer/HexalithApp.ApiServer.csproj' /t:PublishContainer --configuration Release --os linux --arch x64 -p:ContainerImageTags='"${{ env.VERSION }};latest"' -p:ContainerRegistry=${{ vars.AZURE_REGISTRY }} -p:ContainerRepository='security-api'
    - name: Log in to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_APPLICATIONID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID  }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        allow-no-subscriptions: true
    - name: Deploy to Azure Container Apps
      run: az account show
    - name: Deploy to Azure Container Apps
      run: |
        az containerapp update \
          --name int-security-web \
          --resource-group hex-integration \
          --image ${{ vars.AZURE_REGISTRY }}/security-web:${{ env.VERSION }}
 
    - name: Deploy to Azure Container Apps
      run: |
        az containerapp update \
          --name int-security-api \
          --resource-group hex-integration \
          --image ${{ vars.AZURE_REGISTRY }}/security-api:${{ env.VERSION }}
 
